services:
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - words

  words:
    build: ./words
    expose:
      - "8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    build: ./db
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5